name: Conda MoviePy Test

on:
  workflow_dispatch:

jobs:
  conda-moviepy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10
          miniforge-variant: Mambaforge
          channels: conda-forge

      - name: Create Conda env and install moviepy
        run: |
          mamba create -n videoenv -y python=3.10 moviepy
          echo "conda activate videoenv" >> ~/.bashrc
          source ~/.bashrc

      - name: Run MoviePy test
        shell: bash -l {0}
        run: |
          conda activate videoenv
          echo "from moviepy.editor import ImageClip; print('✅ MoviePy via conda')" > test_import.py
          python test_import.py
