name: Debug MoviePy Installation

on:
  workflow_dispatch:

jobs:
  debug-moviepy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install only moviepy
        run: |
          python -m pip install --upgrade pip
          pip install moviepy

      - name: Show installed packages
        run: pip list

      - name: Test moviepy import
        run: |
          echo "from moviepy.editor import ImageClip; print('✅ MoviePy import success')" > test_import.py
          python test_import.py
