name: Run Docker Video Creator

on:
  workflow_dispatch:

jobs:
  run-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t prodpick-video .

      - name: Create output folder
        run: mkdir -p output

      - name: Run container to generate video
        run: docker run -v ${{ github.workspace }}/output:/app/output prodpick-video

      - name: Upload output video
        uses: actions/upload-artifact@v4
        with:
          name: video-output
          path: output/*.mp4
