name: Python Build & Test Full

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install all dependencies
        run: |
          pip install --no-cache-dir \
            flask==2.3.3 \
            gunicorn==20.1.0 \
            moviepy==2.2.1 \
            numpy==1.25.2 \
            pillow==11.3.0 \
            gTTS==2.5.4 \
            openai==1.101.0 \
            requests==2.32.5 \
            beautifulsoup4==4.13.4 \
            playwright==1.54.0 \
            imageio==2.37.0 \
            imageio-ffmpeg==0.6.0 \
            python-dotenv==1.1.1 \
            proglog==0.1.12 \
            pydantic==2.11.7 \
            pydantic-core==2.33.2 \
            blinker==1.9.0 \
            jinja2==3.1.6 \
            itsdangerous==2.2.0 \
            click==8.1.8 \
            tqdm==4.67.1 \
            sniffio==1.3.1 \
            typing-inspection==0.4.1 \
            typing-extensions==4.14.1 \
            soupsieve==2.7 \
            annotated-types==0.7.0 \
            anyio==4.10.0 \
            httpx==0.28.1 \
            httpcore==1.0.9 \
            h11==0.16.0 \
            greenlet==3.2.4 \
            distro==1.9.0 \
            idna==3.10 \
            urllib3==2.5.0 \
            certifi==2025.8.3 \
            markupsafe==3.0.2

      - name: Verify imports
        run: |
          python -c "import flask; import moviepy.editor; import numpy; import requests; import gtts; import openai; import playwright; import imageio; import imageio_ffmpeg; import beautifulsoup4; print('✅ All imports OK')"
