name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install numpy first (Python 3.11 compatible)
      run: pip install --force-reinstall --no-cache-dir numpy==1.26.4

    - name: Install remaining dependencies
      run: |
        pip install --no-cache-dir \
          flask==2.3.3 \
          gunicorn==20.1.0 \
          moviepy==2.1.2 \
          Pillow==10.1.0 \
          gTTS==2.3.1 \
          requests==2.31.0 \
          openai==1.29.0 \
          python-dotenv==1.0.0 \
          imageio==2.31.1 \
          imageio-ffmpeg==0.6.0 \
          beautifulsoup4 \
          lxml \
          jinja2

    - name: Test imports
      run: |
        python -c "import flask; import moviepy.editor; import numpy; import requests; print('All imports OK')"
