name: Python App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Verify imports
      run: |
        python -c "import flask; import moviepy.editor; import numpy; import requests; print('✅ All imports OK')"

    - name: Run Flask (test)
      run: |
        nohup python app.py &
        sleep 5
        curl -f http://127.0.0.1:3000/ || (echo "App did not start" && exit 1)
