name: Upload Video to YouTube

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Create client_secret.json from secret
        run: echo "${{ secrets.YOUTUBE_CLIENT_SECRET }}" > client_secret.json

      - name: Run uploader
        run: python main.py
